version: '3'

services:
    sloganpicker-frontend:
        build:
            context: ./
            dockerfile: provisioning/frontend.dockerfile
        volumes:
            - ./src:/srv/app/sloganpicker
        ports:
            - "127.0.0.1:10000:3000"
